### ISSUE TITLE
if we don't set the access modifier it's public by default 

### ISSUE THREAD

**Issue by tia337** [goveo/euro-diffusion#2]
https://github.com/goveo/euro-diffusion/blob/3f64dd8d2d876eb33993cdcc41efb455370cb867/classes/map.ts#L13
https://github.com/goveo/euro-diffusion/blob/3f64dd8d2d876eb33993cdcc41efb455370cb867/classes/map.ts#L18

**Comment by ybrusentsov** [comment]
Fixed
