### ISSUE TITLE
Maximum values

### ISSUE THREAD

**Issue by IanaKhitsko** [goveo/euro-diffusion#4]
https://github.com/goveo/euro-diffusion/blob/8d34fe3d376eac884f1b8ed54a823c523f3cc05c/src/classes/map.ts#L50

https://github.com/goveo/euro-diffusion/blob/8d34fe3d376eac884f1b8ed54a823c523f3cc05c/src/classes/map.ts#L52

What if country.coordinates.yh or country.coordinates.yl will be 9999 ?

**Comment by ybrusentsov** [comment]
Country coordinates can not be between its min/max values declared in the `Country` class:
https://github.com/goveo/euro-diffusion/blob/8d34fe3d376eac884f1b8ed54a823c523f3cc05c/src/classes/country.ts#L10-L16

There is a check for the validity of coordinates in `Country` constructor:
https://github.com/goveo/euro-diffusion/blob/8d34fe3d376eac884f1b8ed54a823c523f3cc05c/src/classes/country.ts#L25-L28
https://github.com/goveo/euro-diffusion/blob/8d34fe3d376eac884f1b8ed54a823c523f3cc05c/src/classes/country.ts#L41-L57
