### ISSUE TITLE
Do you ever reach this line? 

### ISSUE THREAD

**Issue by IanaKhitsko** [goveo/euro-diffusion#8]
https://github.com/goveo/euro-diffusion/blob/8d34fe3d376eac884f1b8ed54a823c523f3cc05c/src/classes/map.ts#L160

It this line reachable ? It seems all countries should have number of days if upper condition  "this.isCompleted() == true", no?

**Comment by ybrusentsov** [comment]
### Yes, this line is reachable.

This line
https://github.com/goveo/euro-diffusion/blob/8d34fe3d376eac884f1b8ed54a823c523f3cc05c/src/classes/map.ts#L155
is reached before
https://github.com/goveo/euro-diffusion/blob/8d34fe3d376eac884f1b8ed54a823c523f3cc05c/src/classes/map.ts#L142
So the last country will not be in the resulting map.

In these lines, we adding countries that finished diffusion on the last day
https://github.com/goveo/euro-diffusion/blob/8d34fe3d376eac884f1b8ed54a823c523f3cc05c/src/classes/map.ts#L158-L162
